# frozen_string_literal: true

source "https://rubygems.org"

# Script
gem 'shopify_api'
gem 'dotenv'
gem 'rake'
 
 
# Debugging
gem 'pry'
 
# Testing
gem 'minitest'

git_source(:github) {|repo_name| "https://github.com/#{repo_name}" }

# gem "rails"
